dmenu_theme

diff --git a/.local/bin/dm-run b/.local/bin/dm-run
--- a/.local/bin/dm-run
+++ b/.local/bin/dm-run
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
-#
+
 # Script name: dm-run
 # Description: The standard dmenu_run command with flags and a prompt.
-# Dependencies: dmenu
+# Dependencies: dmenu, xdotool
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Derek Taylor
@@ -13,5 +13,87 @@
 set -euo pipefail
 
 export _JAVA_AWT_WM_NONREPARENTING=1
-exec $(dmenu_path | dmenu -l 20 -g 3 -X 0 -Y 0 -W 680 -p 'Run: ' "$@")
 
+if [[ -f ~/xos/theme/.dmenu_theme ]] && [[ -f ~/xos/theme/.dmenu_position ]] && [[ -f ~/xos/theme/.dmenu_y_position ]]; then
+    dmenu_colors=($(cat ~/xos/theme/.dmenu_theme))
+    x_position=$(cat ~/xos/theme/.dmenu_position)
+    y_position=$(cat ~/xos/theme/.dmenu_y_position)
+else
+    dmenu_colors=()
+    x_position="-X 0"
+    y_position="-Y 0"
+fi
+
+active_window=$(xdotool getactivewindow || true)
+
+# If a window is active
+if [[ -n "$active_window" ]]; then
+    window_class=$(xdotool getwindowname $active_window)
+
+    # if emacs is focused, always open at the bottom right, irrespective of the theme
+    if [[ $window_class == *"Emacs"* ]]; then
+        x_position="-X 1239" # change this to your desired X position for Emacs
+        y_position="-Y 0"  # change this to your desired Y position for Emacs
+    fi
+fi
+
+exec $(dmenu_path | dmenu "${dmenu_colors[@]}" -l 20 -g 3 $x_position $y_position -W 680 -p 'Run: ' "$@")
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# #!/usr/bin/env bash
+# #
+# # Script name: dm-run
+# # Description: The standard dmenu_run command with flags and a prompt.
+# # Dependencies: dmenu, xdotool
+# # GitLab: https://www.gitlab.com/dwt1/dmscripts
+# # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
+# # Contributors: Derek Taylor
+
+# # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# # if certain things happen, which is a good thing.  Otherwise, we can
+# # get hidden bugs that are hard to discover.
+# set -euo pipefail
+
+# export _JAVA_AWT_WM_NONREPARENTING=1
+
+# if [[ -f ~/xos/theme/.dmenu_theme ]] && [[ -f ~/xos/theme/.dmenu_position ]] && [[ -f ~/xos/theme/.dmenu_y_position ]]; then
+#     dmenu_colors=($(cat ~/xos/theme/.dmenu_theme))
+#     x_position=$(cat ~/xos/theme/.dmenu_position)
+#     y_position=$(cat ~/xos/theme/.dmenu_y_position)
+# else
+#     dmenu_colors=()
+#     x_position="-X 0"
+#     y_position="-Y 0"
+# fi
+
+# active_window=$(xdotool getactivewindow)
+# window_class=$(xdotool getwindowname $active_window)
+
+# # if emacs is focused, always open at the bottom right, irrespective of the theme
+# if [[ $window_class == *"Emacs"* ]]; then
+#     x_position="-X 1239" # change this to your desired X position for Emacs
+#     y_position="-Y 0"  # change this to your desired Y position for Emacs
+# fi
+
+# exec $(dmenu_path | dmenu "${dmenu_colors[@]}" -l 20 -g 3 $x_position $y_position -W 680 -p 'Run: ' "$@")
